"""The data quality rules, one entry per rule.

Every predicate is written so that it is TRUE for a row that FAILS the rule. Run the
predicate and the rows it returns are the problem rows.

`finding` is one of: defect, business rule, documentation gap, open question, none.
`reading` says why. Both are a first reading from the data alone and are meant to be
confirmed or corrected by someone who owns the source.
"""

RULES = [
    {
        "id": "CMP-01",
        "name": "Originating base is recorded",
        "dimension": "Completeness",
        "severity": "low",
        "test": "Every trip names the base that received the original request.",
        "why": "Without it, trips cannot be traced back to the base that took the booking.",
        "predicate": "originating_base_num IS NULL",
        "example_columns": ["originating_base_num", "dispatching_base_num"],
        "finding": "business rule",
        "reading": "Almost every Lyft trip leaves this blank and no Uber trip does. One company does not report the field, so this is how the feed works rather than missing data.",
    },
    {
        "id": "CMP-02",
        "name": "Pickup zone is a real city zone",
        "dimension": "Completeness",
        "severity": "medium",
        "test": "Every trip starts in a named New York City taxi zone, not 'unknown' or 'outside the city'.",
        "why": "Demand by area is only as good as the pickup zone on each trip.",
        "predicate": "PULocationID IN (264, 265)",
        "example_columns": ["PULocationID", "DOLocationID"],
        "finding": "open question",
        "reading": "A small number of trips start outside the city. These may be legitimate return trips or bad zone matching. Needs an answer from the source.",
    },
    {
        "id": "CMP-03",
        "name": "Dropoff zone is known",
        "dimension": "Completeness",
        "severity": "low",
        "test": "Every trip ends in a known zone. Ending outside the city is allowed; 'unknown' is not.",
        "why": "Trips with no destination cannot be used for route or area planning.",
        "predicate": "DOLocationID = 264",
        "example_columns": ["PULocationID", "DOLocationID"],
        "finding": "defect",
        "reading": "Only Uber trips carry the 'unknown' dropoff code. The count is tiny, and the destination was simply not captured.",
    },
    {
        "id": "VAL-01",
        "name": "Fare is not negative",
        "dimension": "Validity",
        "severity": "medium",
        "test": "The base passenger fare is zero or more.",
        "why": "Negative fares pull revenue totals down and usually mean a refund was recorded as a trip.",
        "predicate": "base_passenger_fare < 0",
        "example_columns": ["base_passenger_fare", "driver_pay", "trip_miles"],
        "finding": "business rule",
        "reading": "Nearly all are Uber trips. They look like refunds or adjustments booked against the trip, which is a real event, but the specification does not say so.",
    },
    {
        "id": "VAL-02",
        "name": "Trip distance is above zero",
        "dimension": "Validity",
        "severity": "medium",
        "test": "Every trip covers some distance.",
        "why": "A trip of zero miles is either a cancellation counted as a trip or a failed distance reading.",
        "predicate": "trip_miles <= 0",
        "example_columns": ["trip_miles", "trip_time", "base_passenger_fare"],
        "finding": "defect",
        "reading": "A completed trip cannot be zero miles long. These inflate trip counts slightly and drag down average distance.",
    },
    {
        "id": "VAL-03",
        "name": "Driver pay is not negative",
        "dimension": "Validity",
        "severity": "low",
        "test": "The driver is paid zero or more for the trip.",
        "why": "Negative pay distorts the driver share of fares.",
        "predicate": "driver_pay < 0",
        "example_columns": ["driver_pay", "base_passenger_fare"],
        "finding": "open question",
        "reading": "Very rare. Likely clawbacks recorded on the trip, but the count is too small to tell.",
    },
    {
        "id": "CON-01",
        "name": "Dropoff is after pickup",
        "dimension": "Consistency",
        "severity": "high",
        "test": "The dropoff time is not earlier than the pickup time.",
        "why": "A trip that ends before it starts has a negative duration and breaks every time-based measure.",
        "predicate": "dropoff_datetime < pickup_datetime",
        "example_columns": ["pickup_datetime", "dropoff_datetime", "trip_time"],
        "finding": "documentation gap",
        "reading": "All but two of these fall on 2 November 2025, the night the clocks went back. Times are stored as local clock time with no offset, so trips that crossed 2am appear to run backwards.",
    },
    {
        "id": "CON-02",
        "name": "Request comes before pickup",
        "dimension": "Consistency",
        "severity": "high",
        "test": "The ride was requested no later than the rider was picked up.",
        "why": "Wait time is pickup minus request. If the request is later, the wait is negative and the trip drops out of the wait figures.",
        "predicate": "request_datetime > pickup_datetime",
        "example_columns": ["request_datetime", "pickup_datetime"],
        "finding": "open question",
        "reading": "About one trip in eighty, from both companies, typically with the request stamped six minutes after pickup. This is the check that matters most for the wait time figures, and the data alone cannot explain it.",
    },
    {
        "id": "CON-03",
        "name": "Driver arrives before pickup",
        "dimension": "Consistency",
        "severity": "medium",
        "test": "The driver's arrival time is not later than the pickup time.",
        "why": "A driver cannot start a trip before reaching the rider.",
        "predicate": "on_scene_datetime > pickup_datetime",
        "example_columns": ["on_scene_datetime", "pickup_datetime"],
        "finding": "defect",
        "reading": "Rare, and almost all Uber. The two timestamps are out of order.",
    },
    {
        "id": "CON-04",
        "name": "Trip time matches the timestamps",
        "dimension": "Consistency",
        "severity": "medium",
        "test": "The recorded trip time is within one minute of dropoff time minus pickup time.",
        "why": "If the two disagree, duration and speed depend on which one a report happens to use.",
        "predicate": "abs(date_diff('second', pickup_datetime, dropoff_datetime) - trip_time) > 60",
        "example_columns": ["pickup_datetime", "dropoff_datetime", "trip_time"],
        "finding": "open question",
        "reading": "Almost entirely Lyft, and it starts in May 2026. Before then the two agree; since then about one Lyft trip in ten records a trip time a couple of minutes longer than its timestamps. Something changed in how Lyft reports trip time that month.",
    },
    {
        "id": "REA-01",
        "name": "Speed is believable",
        "dimension": "Reasonableness",
        "severity": "low",
        "test": "Distance divided by time comes to 80 miles an hour or less.",
        "why": "An impossible speed means the distance or the time is wrong.",
        "predicate": "trip_time > 0 AND trip_miles / (trip_time / 3600.0) > 80",
        "example_columns": ["trip_miles", "trip_time"],
        "finding": "defect",
        "reading": "A handful of trips with a distance or duration that cannot be right.",
    },
    {
        "id": "REA-02",
        "name": "Wait is under an hour",
        "dimension": "Reasonableness",
        "severity": "low",
        "test": "The rider was picked up within an hour of requesting.",
        "why": "Very long waits are more likely rides booked ahead than real waits, and they stretch the averages.",
        "predicate": "date_diff('second', request_datetime, pickup_datetime) > 3600",
        "example_columns": ["request_datetime", "pickup_datetime"],
        "finding": "business rule",
        "reading": "Most likely rides scheduled in advance, where the request time is when the booking was made.",
    },
    {
        "id": "TIM-01",
        "name": "Trip is in the right month's file",
        "dimension": "Timeliness",
        "severity": "medium",
        "test": "The pickup date falls in the month named on the file it arrived in.",
        "why": "Trips filed under the wrong month shift the monthly totals.",
        "predicate": "strftime(pickup_datetime, '%Y-%m') <> file_month",
        "example_columns": ["pickup_datetime", "file_month"],
        "finding": "none",
        "reading": "No failures. Every trip sits in the right month.",
    },
]
